syntax = "proto3";
package  push;

option go_package = "push/v1";



enum Platform {
  PLATFORM_UNKNOWN = 0;
  PLATFORM_ANDROID = 1;
  PLATFORM_IOS = 2;
  PLATFORM_WEB = 3;
}

message AddDeviceRequest {
  string user_id = 1;
  string device_id = 2;
  Platform platform = 3;
}

message AddDeviceResponse {
  bool success = 1;
  string error = 2;
}

message GetDevicesRequest {
  string user_id = 1;
}

message Device {
  string device_id = 1;
  Platform platform = 2;
}

message GetDevicesResponse {
  repeated Device devices = 1;
}

service PushService {
  rpc AddDevice(AddDeviceRequest) returns (AddDeviceResponse);
  rpc GetDevices(GetDevicesRequest) returns (GetDevicesResponse);
}



